name: 'build macos'

on:
  workflow_call:
    inputs:
      cmake-version:
        required: true
        type: string
      platforms:
        required: true
        type: string
      configurations:
        required: true
        type: string

jobs:
  build:
    runs-on: macos-latest
    strategy:
        matrix:
            platform: ${{ fromJson(inputs.platforms) }}
            config: ${{ fromJson(inputs.configurations) }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
            submodules: 'true'
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2.0.2
        with:
            cmake-version: ${{ inputs.cmake-version }}
      - name: CMake Configure
        run: cmake -G Xcode -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/Build/CMake/ios.toolchain.cmake" -DPLATFORM=OS -DDEPLOYMENT_TARGET="10.11" -DENABLE_UNIT_TESTS="OFF" -B ./built/Int/cmake_${{ matrix.platform }} .
      - name: CMake Build
        run: cmake --build . --target install --config ${{ matrix.config }}
        working-directory: ./built/Int/cmake_${{ matrix.platform }}