name: Nightly build

on:
  workflow_dispatch:
  schedule:
    - cron: 0 23 * * 1-5

jobs:
    # Windows
    build-windows:
      uses: ./.github/workflows/windows.yml
      with:
        cmake-version: '3.26.3'
        platforms: "['x64', 'Win32', 'ARM', 'ARM64']"
        configurations: "['Release', 'Debug']"
    # MacOS
    build-macos:
      uses: ./.github/workflows/macos.yml
      with:
        cmake-version: '3.26.3'
    # iOS
    build-ios:
      uses: ./.github/workflows/ios.yml
      with:
        cmake-version: '3.26.3'