name: 'build windows'

on:
  workflow_call:
    inputs:
      cmake-version:
        required: true
        type: string
      platforms:
        required: true
        type: string
      configurations:
        required: true
        type: string

jobs:
  build:
    runs-on: windows-2019
    strategy:
        matrix:
            platform: ${{ fromJson(inputs.platforms) }}
            config: ${{ fromJson(inputs.configurations) }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
            submodules: 'true'
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2.0.2
        with:
            cmake-version: ${{ inputs.cmake-version }}
      - name: Make Solution Directory
        run: mkdir built && 
            cd built &&
            mkdir Int &&
            cd Int && 
            mkdir cmake_${{ matrix.platform }}
      - name: CMake Configure
        run: cmake -G "Visual Studio 16 2019" -A ${{ matrix.platform }} ..\..\..
        working-directory: ./built/Int/cmake_${{ matrix.platform }}
      - name: CMake Build
        run: cmake --build . --target install --config ${{ matrix.config }}
        working-directory: ./built/Int/cmake_${{ matrix.platform }}
      - name: Running Unit Tests
        if: ${{ (matrix.platform == 'x64') || (matrix.platform == 'Win32') }}
        run: .\GLTFSDK.Test.exe --gtest_output=xml:GLTFSDK.Test.log
        working-directory: ./built/Out/windows_${{ matrix.platform }}\${{ matrix.config }}\GLTFSDK.Test
      - uses: actions/upload-artifact@v4
        name: "Upload test results"
        if: ${{ (matrix.platform == 'x64') || (matrix.platform == 'Win32') }}
        with:
            name: GLTFSDK.Test.Windows.${{ matrix.platform }}.${{ matrix.config }}
            path: ${{ github.workspace }}\built\Out\windows_${{ matrix.platform }}\${{ matrix.config }}\GLTFSDK.Test\GLTFSDK.Test.log